/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Vb0tFtZGfSs
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"

export function Component() {
  return (<>
    <Card className="max-w-md mx-auto">
      <CardHeader className="space-y-2">
        <CardTitle className="text-3xl">Activities</CardTitle>
        <CardDescription>List of activities with options to edit or delete.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <Button className="ml-auto">Add New Activity</Button>
        <div className="grid grid-cols-2 gap-4">
          <div className="relative group overflow-hidden rounded-lg">
            <Link className="absolute inset-0 z-10" href="#">
              <span className="sr-only">View</span>
            </Link>
            <img
              alt="Activity 1"
              className="object-cover w-full h-60"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/300",
                objectFit: "cover",
              }}
              width={400} />
          </div>
          <div className="relative group overflow-hidden rounded-lg">
            <Link className="absolute inset-0 z-10" href="#">
              <span className="sr-only">View</span>
            </Link>
            <img
              alt="Activity 2"
              className="object-cover w-full h-60"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/300",
                objectFit: "cover",
              }}
              width={400} />
          </div>
          <div className="relative group overflow-hidden rounded-lg">
            <Link className="absolute inset-0 z-10" href="#">
              <span className="sr-only">View</span>
            </Link>
            <img
              alt="Activity 3"
              className="object-cover w-full h-60"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/300",
                objectFit: "cover",
              }}
              width={400} />
          </div>
          <div className="relative group overflow-hidden rounded-lg">
            <Link className="absolute inset-0 z-10" href="#">
              <span className="sr-only">View</span>
            </Link>
            <img
              alt="Activity 4"
              className="object-cover w-full h-60"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/300",
                objectFit: "cover",
              }}
              width={400} />
          </div>
        </div>
        <Button className="ml-auto mt-4 lg:mt-0">Logout</Button>
      </CardContent>
    </Card>
    <div className="grid w-full max-w-sm items-center gap-1.5">
      <Label htmlFor="image">Upload Image</Label>
      <Input id="image" type="file" />
    </div>
  </>);
}
